name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main  # Change to 'master' if your branch is named that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload static site files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Uploads everything in your repository (index.html, about.html, etc.)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2